packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/install-pkg': ^1.1.0
  '@clack/prompts': ^0.11.0
  '@vue/compiler-dom': ^3.5.16
  '@vue/compiler-sfc': ^3.5.16
  chalk: ^4.1.2
  commander: ^7.2.0
  commondir: ^1.0.1
  debug: ^4.3.4
  dependency-cruiser: ^17.0.1
  local-pkg: ^1.1.1
  ora: ^5.4.1
  pluralize: ^8.0.0
  pretty-ms: ^7.0.1
  rc: ^1.2.8
  stream-to-array: ^2.3.0
  ts-graphviz: ^2.1.2
  tsconfig-paths: ^4.2.0
  walkdir: ^0.4.1

catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    bumpp: ^10.1.0
    consola: ^3.4.2
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsdown: ^0.13.0
    tsx: ^4.19.3
    typescript: ^5.8.2
    vite: ^6.2.1
  testing:
    vitest: ^3.0.8
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
