packages:
  - playground
  - docs
  - packages/*
  - examples/*
patchedDependencies:
  dependency-tree: patches/dependency-tree.patch
catalog:
  '@antfu/install-pkg': ^1.1.0
  '@clack/prompts': ^0.11.0
  '@types/madge': ^5.0.3
  '@vue/compiler-dom': ^3.5.16
  '@vue/compiler-sfc': ^3.5.16
  dependency-tree: 11.1.1
  local-pkg: ^1.1.1
  madge: ^8.0.0
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    bumpp: ^10.1.0
    consola: ^3.4.2
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.1
  testing:
    vitest: ^3.0.8
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
